name: Deploy VS Code Extension

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar o VSCE globalmente
        run: npm install -g @vscode/vsce

      - name: Empacotar a extensão (.vsix)
        run: vsce package

      - name: Encontrar o arquivo .vsix gerado
        id: get_vsix
        run: |
          VSIX_FILE=$(ls *.vsix)
          echo "file_name=$VSIX_FILE" >> $GITHUB_OUTPUT

      - name: Adicionar .vsix ao download da Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.get_vsix.outputs.file_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
